### ISSUE TITLE
How to obtain the onnx model through self trained models

### ISSUE THREAD

**Issue by Hafuhafuha** [arsenyinfo/EnlightenGAN-inference#6]
Dear author, thank you very much for your contribution. As a student, I am currently trying to convert my trained EnlightenGAN weights to onnx to test if there will be any improvement in running efficiency. However, after multiple attempts, I have failed and cannot obtain the correct onnx file. Could you please provide me with some conversion files or helpful tips for my reference? Thank you again for your help

**Comment by arsenyinfo** [comment]
Hey @Hafuhafuha, unfortunately I don't have any conversion scripts left. I can try reviewing your conversion script if that helps

**Comment by Hafuhafuha** [comment]
Dear author, thank you for your reply! The method I adopted was to add the following code to the source code of the EnlightenGAN project based on the predict.py file:
def Convert_ONNX():
    # set the model to inference mode
    model.netG_A.eval()
    # Let's create a dummy input tensor
    dummy_input = torch.randn(1,3,256,256)
    # Export the model
    torch.onnx.export(
        model,  
        dummy_input,  
        "EnlightenGAN.onnx",  
        export_params=True,  
        opset_version=10,  
        do_constant_folding=True,  
        input_names=['input'],  
        output_names=['output'],  
        dynamic_axes={
            'input': {0: 'batch_size', 2: 'height', 3: 'width'},  
            'output': {0: 'batch_size', 2: 'height', 3: 'width'}
        }
    )
    print('Model has been converted to ONNX')
    ___________________________________________________________________________________________
    In my understanding, converting to an onnx model requires loading the weight file into the model instance and defining a dynamic input tensor to adapt to EnlightenGAN. But the following error occurred:
    Traceback (most recent call last):
  File "predict.py", line 63, in <module>
    Convert_ONNX()
  File "predict.py", line 17, in Convert_ONNX
    torch.onnx.export(
  File "D:\Anaconda\envs\detectron2\lib\site-packages\torch\onnx\__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "D:\Anaconda\envs\detectron2\lib\site-packages\torch\onnx\utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "D:\Anaconda\envs\detectron2\lib\site-packages\torch\onnx\utils.py", line 701, in _export
    with exporter_context(model, training):
  File "D:\Anaconda\envs\detectron2\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\detectron2\lib\site-packages\torch\onnx\utils.py", line 102, in exporter_context
    with select_model_mode_for_export(model, mode) as mode_ctx, \
  File "D:\Anaconda\envs\detectron2\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\detectron2\lib\site-packages\torch\onnx\utils.py", line 41, in select_model_mode_for_export
    is_originally_training = model.training
AttributeError: 'SingleModel' object has no attribute 'training'
____________________________________________________________________________________________________________
I don't know how to correct this error. I hope you can guide me to export the onnx model correctly. Thank you again!

**Comment by scottcali** [comment]
Hi,

    Same question how to convert to onnx?

    Thanks!

-Scott

**Comment by scottcali** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/214_EnlightenGAN/convert_script.txt

**Comment by Hafuhafuha** [comment]
@scottcali Thank you very much, it has been very helpful to me

**Comment by spsingh37** [comment]
@Hafuhafuha Hi, could you please share how you were able to obtain the onnx model?

**Comment by Hafuhafuha** [comment]
@spsingh37 I'm sorry I didn't follow up on this issue
